codecov:
  require_ci_to_pass: false
  token: # 可選：如果需要上傳到 codecov.io，添加 token

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        branches:
          - main
          - develop
    patch:
      default:
        target: 70%
        threshold: 1%
        base: auto

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false

ignore:
  - "**/tests/**"
  - "**/test_*.py"
  - "**/__pycache__/**"
  - "**/migrations/**"
  - "**/alembic/**"
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/dist/**"
  - "**/build/**"

