#!/bin/bash
# ============================================================
# 修复 DNS 解析和软件源问题
# ============================================================
# 
# 功能：
# 1. 诊断 DNS 解析问题
# 2. 配置可靠的 DNS 服务器
# 3. 更换为可靠的软件源（阿里云/清华大学镜像）
# 4. 测试网络连接
# ============================================================

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

success_msg() { echo -e "${GREEN}✅ $1${NC}"; }
error_msg() { echo -e "${RED}❌ $1${NC}"; }
info_msg() { echo -e "${YELLOW}ℹ️  $1${NC}"; }
step_msg() { echo -e "${BLUE}📌 $1${NC}"; }

echo "========================================="
echo "修复 DNS 解析和软件源问题"
echo "========================================="
echo ""

# 检查是否以 root 权限运行
if [ "$EUID" -ne 0 ]; then 
    error_msg "请使用 sudo 运行此脚本"
    exit 1
fi

# ============================================================
# 第一部分：诊断 DNS 问题
# ============================================================
echo "========================================="
echo "第一部分：诊断 DNS 问题"
echo "========================================="
echo ""

step_msg "[1/3] 检查当前 DNS 配置..."

# 检查 systemd-resolved
if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
    info_msg "systemd-resolved 正在运行"
    cat /etc/systemd/resolved.conf | grep -E "^DNS=|^FallbackDNS=" || echo "使用默认 DNS"
else
    info_msg "systemd-resolved 未运行或不存在"
fi

# 检查 /etc/resolv.conf
if [ -f /etc/resolv.conf ]; then
    info_msg "当前 /etc/resolv.conf 配置:"
    cat /etc/resolv.conf
else
    info_msg "/etc/resolv.conf 不存在"
fi
echo ""

step_msg "[2/3] 测试 DNS 解析..."

# 测试解析
test_dns() {
    local hostname=$1
    if host "$hostname" > /dev/null 2>&1 || nslookup "$hostname" > /dev/null 2>&1; then
        success_msg "可以解析: $hostname"
        return 0
    else
        error_msg "无法解析: $hostname"
        return 1
    fi
}

test_dns "google.com" || DNS_FAILED=true
test_dns "baidu.com" || DNS_FAILED=true
test_dns "mirrors.ucloud.cn" || DNS_FAILED=true

if [ "$DNS_FAILED" = "true" ]; then
    error_msg "DNS 解析失败，需要修复"
else
    success_msg "DNS 解析正常"
fi
echo ""

step_msg "[3/3] 测试网络连接..."

if ping -c 2 8.8.8.8 > /dev/null 2>&1; then
    success_msg "可以连接到外网（IP 连接正常）"
    NETWORK_OK=true
else
    error_msg "无法连接到外网"
    NETWORK_OK=false
fi

if ping -c 2 114.114.114.114 > /dev/null 2>&1; then
    success_msg "可以连接到国内 DNS（114.114.114.114）"
else
    info_msg "无法连接到 114.114.114.114"
fi
echo ""

# ============================================================
# 第二部分：修复 DNS 配置
# ============================================================
echo "========================================="
echo "第二部分：修复 DNS 配置"
echo "========================================="
echo ""

if [ "$NETWORK_OK" = "true" ]; then
    step_msg "[1/2] 配置可靠的 DNS 服务器..."
    
    # 配置 systemd-resolved（Ubuntu 22.04 默认使用）
    if command -v systemd-resolve > /dev/null 2>&1 || systemctl list-unit-files | grep -q systemd-resolved; then
        info_msg "配置 systemd-resolved..."
        
        # 备份原配置
        cp /etc/systemd/resolved.conf /etc/systemd/resolved.conf.backup 2>/dev/null || true
        
        # 配置 DNS
        cat > /etc/systemd/resolved.conf << 'EOF'
[Resolve]
DNS=223.5.5.5 114.114.114.114 8.8.8.8
FallbackDNS=1.1.1.1 8.8.4.4
Domains=
#DNSOverTLS=no
#MulticastDNS=no
#DNSSEC=no
#Cache=yes
#DNSStubListener=yes
#ReadEtcHosts=yes
EOF
        
        systemctl restart systemd-resolved 2>/dev/null || true
        success_msg "systemd-resolved 配置已更新"
    fi
    
    # 同时更新 /etc/resolv.conf（作为备用）
    info_msg "更新 /etc/resolv.conf..."
    cat > /etc/resolv.conf << 'EOF'
# Generated by fix-dns-and-sources.sh
nameserver 223.5.5.5
nameserver 114.114.114.114
nameserver 8.8.8.8
EOF
    
    success_msg "DNS 配置已更新"
    echo ""
    
    step_msg "[2/2] 验证 DNS 解析..."
    sleep 2
    
    if host "google.com" > /dev/null 2>&1 || nslookup "google.com" > /dev/null 2>&1; then
        success_msg "DNS 解析已修复"
    else
        error_msg "DNS 解析仍然失败，可能需要检查网络连接"
    fi
    echo ""
else
    error_msg "网络连接失败，无法修复 DNS"
    echo "请检查："
    echo "  1. 服务器的网络连接"
    echo "  2. 防火墙设置"
    echo "  3. 路由配置"
    exit 1
fi

# ============================================================
# 第三部分：更换软件源
# ============================================================
echo "========================================="
echo "第三部分：更换软件源"
echo "========================================="
echo ""

step_msg "[1/3] 备份原有软件源配置..."

# 备份原有配置
if [ -f /etc/apt/sources.list ]; then
    cp /etc/apt/sources.list /etc/apt/sources.list.backup.$(date +%Y%m%d_%H%M%S)
    success_msg "已备份 /etc/apt/sources.list"
fi

if [ -d /etc/apt/sources.list.d ]; then
    tar -czf /etc/apt/sources.list.d.backup.$(date +%Y%m%d_%H%M%S).tar.gz /etc/apt/sources.list.d/ 2>/dev/null || true
fi
echo ""

step_msg "[2/3] 检测 Ubuntu 版本..."

# 检测 Ubuntu 版本
if [ -f /etc/os-release ]; then
    . /etc/os-release
    UBUNTU_VERSION=$(echo $VERSION_ID | cut -d. -f1,2)
    UBUNTU_CODENAME=$VERSION_CODENAME
    
    info_msg "检测到 Ubuntu $UBUNTU_VERSION ($UBUNTU_CODENAME)"
else
    error_msg "无法检测 Ubuntu 版本"
    exit 1
fi

# 如果没有检测到 codename，根据版本号设置
if [ -z "$UBUNTU_CODENAME" ]; then
    case "$UBUNTU_VERSION" in
        22.04)
            UBUNTU_CODENAME="jammy"
            ;;
        20.04)
            UBUNTU_CODENAME="focal"
            ;;
        18.04)
            UBUNTU_CODENAME="bionic"
            ;;
        *)
            error_msg "不支持的 Ubuntu 版本: $UBUNTU_VERSION"
            exit 1
            ;;
    esac
    info_msg "使用 codename: $UBUNTU_CODENAME"
fi
echo ""

step_msg "[3/3] 更换为阿里云镜像源..."

# 使用阿里云镜像（在中国大陆访问速度较快且稳定）
cat > /etc/apt/sources.list << EOF
# 阿里云 Ubuntu ${UBUNTU_VERSION} 镜像源
# 生成时间: $(date)

# 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
deb https://mirrors.aliyun.com/ubuntu/ ${UBUNTU_CODENAME} main restricted universe multiverse
# deb-src https://mirrors.aliyun.com/ubuntu/ ${UBUNTU_CODENAME} main restricted universe multiverse

deb https://mirrors.aliyun.com/ubuntu/ ${UBUNTU_CODENAME}-updates main restricted universe multiverse
# deb-src https://mirrors.aliyun.com/ubuntu/ ${UBUNTU_CODENAME}-updates main restricted universe multiverse

deb https://mirrors.aliyun.com/ubuntu/ ${UBUNTU_CODENAME}-backports main restricted universe multiverse
# deb-src https://mirrors.aliyun.com/ubuntu/ ${UBUNTU_CODENAME}-backports main restricted universe multiverse

deb https://mirrors.aliyun.com/ubuntu/ ${UBUNTU_CODENAME}-security main restricted universe multiverse
# deb-src https://mirrors.aliyun.com/ubuntu/ ${UBUNTU_CODENAME}-security main restricted universe multiverse

# deb https://mirrors.aliyun.com/ubuntu/ ${UBUNTU_CODENAME}-proposed main restricted universe multiverse
# deb-src https://mirrors.aliyun.com/ubuntu/ ${UBUNTU_CODENAME}-proposed main restricted universe multiverse
EOF

success_msg "软件源已更换为阿里云镜像"
echo ""

# ============================================================
# 第四部分：测试软件源
# ============================================================
echo "========================================="
echo "第四部分：测试软件源"
echo "========================================="
echo ""

step_msg "[1/2] 更新软件包列表..."

# 清理 apt 缓存
apt clean
apt autoclean

# 更新软件包列表
if apt update; then
    success_msg "软件包列表更新成功"
else
    error_msg "软件包列表更新失败"
    echo ""
    echo "尝试使用清华大学镜像源..."
    
    # 备用：使用清华大学镜像
    cat > /etc/apt/sources.list << EOF
# 清华大学 Ubuntu ${UBUNTU_VERSION} 镜像源
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${UBUNTU_CODENAME} main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${UBUNTU_CODENAME}-updates main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${UBUNTU_CODENAME}-backports main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${UBUNTU_CODENAME}-security main restricted universe multiverse
EOF
    
    apt update
    success_msg "已切换到清华大学镜像源"
fi
echo ""

step_msg "[2/2] 测试安装一个简单软件包..."

# 测试安装 curl（通常已经安装）
if dpkg -l | grep -q "^ii.*curl"; then
    success_msg "curl 已安装，软件源工作正常"
else
    info_msg "尝试安装 curl 进行测试..."
    if apt install -y curl; then
        success_msg "软件源工作正常"
    else
        error_msg "软件源仍有问题"
    fi
fi
echo ""

# ============================================================
# 完成
# ============================================================
echo "========================================="
echo "✅ DNS 和软件源修复完成！"
echo "========================================="
echo ""
echo "📊 当前配置："
echo "  - DNS 服务器: 223.5.5.5, 114.114.114.114, 8.8.8.8"
echo "  - 软件源: 阿里云镜像（或清华大学镜像）"
echo ""
echo "🔍 验证命令："
echo "  - 测试 DNS: host google.com"
echo "  - 更新软件包: sudo apt update"
echo "  - 测试安装: sudo apt install -y curl"
echo ""
success_msg "现在可以继续执行部署脚本了！"
